In [5]:
import numpy as np

In [6]:
dataset = np.array([[1,1,0,1,0],[1,1,1,0,1],[0,0,1,0,0],[0,1,0,1,0],[1,0,1,1,1],[0,1,1,1,0],])

In [7]:
print(dataset)

[[1 1 0 1 0]
 [1 1 1 0 1]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 1 1 1]
 [0 1 1 1 0]]


In [8]:
print(dataset[:,0:4])

[[1 1 0 1]
 [1 1 1 0]
 [0 0 1 0]
 [0 1 0 1]
 [1 0 1 1]
 [0 1 1 1]]


In [9]:
print(dataset[:,4])

[0 1 0 0 1 0]


In [10]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [11]:
iris = load_iris()
# features matrix
X = iris.data
# label vector
y = iris.target

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=1)

In [13]:
mlp = MLPClassifier(hidden_layer_sizes=(4,), max_iter=10000)
mlp.fit(X_train, y_train);

In [14]:
y_pred = mlp.predict(X_test)
print('Accuracy: %.2f'% accuracy_score(y_test, y_pred))

Accuracy: 1.00


In [15]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

In [19]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, hl)
        self.fc2 = nn.Linear(hl, 3)
        self.softmax = torch.nn.Softmax(dim=1)

    def forward(self, x):
        out = self.fc1(x)
        out = F.relu(out)
        out = self.fc2(out)
        out = self.softmax(out)
        return out

In [20]:
hl = 4
lr = 0.005
num_epoch = 10000
iris = load_iris()
x, y = iris.data, iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)
net = Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=lr)

In [21]:
for epoch in range(num_epoch):
    x = torch.Tensor(x_train).float()
    y = torch.Tensor(y_train).long()
    optimizer.zero_grad()
    y_pred = net(x)
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()
    
    if epoch % 50 is 0:
        print(loss) # cross entropy

tensor(1.0827, grad_fn=<NllLossBackward>)
tensor(0.9033, grad_fn=<NllLossBackward>)
tensor(0.7933, grad_fn=<NllLossBackward>)
tensor(0.7208, grad_fn=<NllLossBackward>)
tensor(0.6652, grad_fn=<NllLossBackward>)
tensor(0.6340, grad_fn=<NllLossBackward>)
tensor(0.6173, grad_fn=<NllLossBackward>)
tensor(0.6076, grad_fn=<NllLossBackward>)
tensor(0.6014, grad_fn=<NllLossBackward>)
tensor(0.5971, grad_fn=<NllLossBackward>)
tensor(0.5940, grad_fn=<NllLossBackward>)
tensor(0.5917, grad_fn=<NllLossBackward>)
tensor(0.5898, grad_fn=<NllLossBackward>)
tensor(0.5883, grad_fn=<NllLossBackward>)
tensor(0.5870, grad_fn=<NllLossBackward>)
tensor(0.5859, grad_fn=<NllLossBackward>)
tensor(0.5850, grad_fn=<NllLossBackward>)
tensor(0.5842, grad_fn=<NllLossBackward>)
tensor(0.5835, grad_fn=<NllLossBackward>)
tensor(0.5828, grad_fn=<NllLossBackward>)
tensor(0.5823, grad_fn=<NllLossBackward>)
tensor(0.5818, grad_fn=<NllLossBackward>)
tensor(0.5813, grad_fn=<NllLossBackward>)
tensor(0.5808, grad_fn=<NllLossBac

tensor(0.5705, grad_fn=<NllLossBackward>)
tensor(0.5705, grad_fn=<NllLossBackward>)
tensor(0.5705, grad_fn=<NllLossBackward>)
tensor(0.5705, grad_fn=<NllLossBackward>)


In [22]:
x = torch.Tensor(x_test).float()
y = torch.Tensor(y_test).long()
y_pred = net(x)
_, predicted = torch.max(y_pred, 1)

acc = torch.sum(y == predicted).numpy() / len(x_test)
print(acc)

0.9555555555555556
