In [1]:
import numpy as np

In [2]:
dataset = np.array([[1,1,0,1,0],[1,1,1,0,1],[0,0,1,0,0],[0,1,0,1,0],[1,0,1,1,1],[0,1,1,1,0],])

In [3]:
print(dataset)

[[1 1 0 1 0]
 [1 1 1 0 1]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 1 1 1]
 [0 1 1 1 0]]


In [4]:
print(dataset[:,0:4])

[[1 1 0 1]
 [1 1 1 0]
 [0 0 1 0]
 [0 1 0 1]
 [1 0 1 1]
 [0 1 1 1]]


In [5]:
print(dataset[:,4])

[0 1 0 0 1 0]


In [7]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [12]:
iris = load_iris()
# features matrix
X = iris.data
# label vector
y = iris.target

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=1)

In [15]:
mlp = MLPClassifier(hidden_layer_sizes=(4,), max_iter=10000)
mlp.fit(X_train, y_train);

In [16]:
y_pred = mlp.predict(X_test)
print('Accuracy: %.2f'% accuracy_score(y_test, y_pred))

Accuracy: 1.00


In [17]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

In [18]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, hl)
        self.fc2 = nn.Linear(h1, 3)
        self.softmax = torch.nn.Softmax(dim=1)

    def forward(self, x):
        out = self.fc1(x)
        out = F.relu(out)
        out = self.fc2(out)
        out = self.softmax(out)
        return out